//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryController.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordFlight
    {
        public int Id { get; set; }
        public int TableId { get; set; }
        public int UserId { get; set; }
    
        public virtual Table Table { get; set; }
        public virtual User User { get; set; }
    }
}
